### ISSUE TITLE
Failed to decode image

### ISSUE THREAD

**Issue by matifdeveloper** [hsbijarniya/image_editor_plus#80]
```
E/FlutterJNI(16727): android.graphics.ImageDecoder$DecodeException: Failed to create image decoder with message 'unimplemented'Input contained an error.
E/FlutterJNI(16727): 	at android.graphics.ImageDecoder.nCreate(Native Method)
E/FlutterJNI(16727): 	at android.graphics.ImageDecoder.-$$Nest$smnCreate(Unknown Source:0)
E/FlutterJNI(16727): 	at android.graphics.ImageDecoder$ByteBufferSource.createImageDecoder(ImageDecoder.java:254)
E/FlutterJNI(16727): 	at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1981)
E/FlutterJNI(16727): 	at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1973)
E/FlutterJNI(16727): 	at io.flutter.embedding.engine.FlutterJNI.decodeImage(FlutterJNI.java:561)
```

**Comment by Gnanendra18** [comment]
Same issue for me. Any solution ?

**Comment by JiyadAhammad** [comment]
Same issue Facing , Any solution


Exception: Unable to decode image for conversion.
